name: Check aggregateDocs

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  check_aggregateDocs:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # zulu suports complete JDK list
          java-version: 14
          cache: 'gradle'

      - name: Run aggregateDocs
        run: ./gradlew clean aggregateDocs
